version: '2.0'  
# define all services
services: 
#creating larvel server1
  laravel1:
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4000:80"
    # we are depending on the mysql backend
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=adminpanel
      - DB_USERNAME=root
      - DB_PASSWORD=
    restart: always
# creating laravel server2
  laravel2:
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 
    ports:
      - "4001:80"
    # we are depending on the mysql backend
    depends_on:
      - mysql
    #volumes:
      #- ./laravel2:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=adminpanel
      - DB_USERNAME=root
      - DB_PASSWORD=
    restart: always
    
#mysql server 

  mysql:
    # we use the mysql base image, version 5.6.36
    image: mysql:5.6.36
    # we mount a datavolume to make sure we don't loose data
    volumes:
       - ./db_data1:/var/lib/mysql
    # setting some envvars to create the DB
    
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=adminpanel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    depends_on:
      - mysql
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=
  
volumes:  
    db_data:
    